-- Inserir novos usuários da planilha Atualização Scanner-2
-- Usando verificação para evitar duplicatas por email

INSERT INTO public.profiles (nome, email, cpf, area, cargo)
SELECT * FROM (VALUES
  ('Vera Lucia De Sousa Miranda', 'vera.miranda@forvismazars.com', '5824', 'AUDITORIA', 'Senior'),
  ('Marcelo Miranda Braga', 'marcelo.braga@forvismazars.com', '2873', 'AUDITORIA', 'Diretor'),
  ('Rayssa Kelly Cunha Bezerra', 'rayssa.bezerra@forvismazars.com', '9380', 'AUDITORIA', 'Supervisor'),
  ('Vinicius De Souza Oliveira', 'vinicius.soliveira@forvismazars.com', '7781', 'AUDITORIA', 'Assistente'),
  ('Camila De Morais Pessoa', 'camila.pessoa@forvismazars.com', '8750', 'AUDITORIA', 'Senior'),
  ('Matheus Barbosa Da Silva', 'matheus.bsilva@forvismazars.com', '1819', 'AUDITORIA', 'Senior'),
  ('Evelyn Abreu', 'evelyn.abreu@forvismazars.com', '3813', 'BUSINESS DEVELOPMENT', 'Gerente'),
  ('Marta Lohany Valadares De Almeida', 'marta.valadares@forvismazars.com', '7590', 'MARKETING', 'Assistente'),
  ('Felipe Dos Santos', 'felipe.dsantos@forvismazars.com', '2809', 'TI', 'Assistente'),
  ('Aymore Ferrari De Figueiredo', 'aymore.figueiredo@forvismazars.com', '5893', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Carla Marques Alexandre Cavalcante', 'carla.cavalcante@forvismazars.com', '3754', 'BPO- FISCAL DIRETOS', 'Analista'),
  ('Felipe De Souza', 'felipe.de.souza@forvismazars.com', '8827', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Raquel Da Silva Santos Lopes', 'raquel.lopes@forvismazars.com', '2703', 'BPO- FISCAL INDIRETOS', 'Analista'),
  ('Ariane Miranda Ribeiro Ott', 'ariane.ribeiro@forvismazars.com', '4742', 'BPO- CONTÁBIL', 'Analista'),
  ('Michelle De Oliveira', 'michelle.oliveira@forvismazars.com', '9825', 'BPO- FINANCEIRO', 'Analista'),
  ('Elias Lucas Da Silva Junior', 'elias.junior@forvismazars.com', '1793', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Rogerio Ferreira Da Silva', 'rogerio.silva@forvismazars.com', '4883', 'BPO- FINANCEIRO', 'Analista'),
  ('Jeniffer Cristina Nogueira Dos Santos', 'jeniffer.santos@forvismazars.com', '2840', 'BPO- FISCAL INDIRETOS', 'Analista'),
  ('Luiz Carlos Maciel Queiroz Junior', 'luiz.queiroz@forvismazars.com', '1781', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Ana Marilia Silva Ferreira', 'ana.sferreira@forvismazars.com', '4725', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Leandro Romao Niedzielski', 'leandro.niedzielski@forvismazars.com', '1790', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Jullie De Oliveira Souto', 'jullie.souto@forvismazars.com', '6456', 'BPO- IMPLANTAÇÃO NETCORP', 'Assistente'),
  ('Felipe Belmino Dos Santos Cardoso', 'felipe.cardoso@forvismazars.com', '0442', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Michele Dias Castro', 'michele.castro@forvismazars.com', '8801', 'BPO- FINANCEIRO', 'Analista'),
  ('Lilian Carla Batista', 'lilian.batista@forvismazars.com', '3809', 'BPO- FOLHA DE PAGAMENTO', 'Assistente'),
  ('Maiane Da Fonseca Araujo', 'maiane.araujo@forvismazars.com', '7861', 'BPO- CONTÁBIL', 'Analista'),
  ('Aline Dos Santos Costa', 'aline.costa@forvismazars.com', '9748', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Monica Gomes De Sousa', 'monica.gsousa@forvismazars.com', '7778', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Roberto Aparecido Moreira Faustino', 'roberto.faustino@forvismazars.com', '0775', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Adryano Perdomo Muniz', 'adryano.muniz@forvismazars.com', '8730', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Assistente'),
  ('Joice Denise Da Silva Duarte', 'joice.denise@forvismazars.com', '2833', 'BPO- FISCAL INDIRETOS', 'Analista'),
  ('Ana Caroline Alves Lyra Moreira', 'ana.moreira@forvismazars.com', '4771', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Gabriel Macedo Michilles', 'gabriel.michilles@forvismazars.com', '1735', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Monique Ficher De Lima Faustino', 'monique.faustino@forvismazars.com', '2779', 'BPO- IMPLANTAÇÃO RM', 'Analista'),
  ('Raquel De Mello Santos Correa', 'raquel.correa@forvismazars.com', '4711', 'BPO- FISCAL INDIRETOS', 'Analista'),
  ('Aline Dos Santos', 'aline.santos@forvismazars.com', '9822', 'BPO- FINANCEIRO', 'Analista'),
  ('Calebi Alves Oliveira', 'calebi.oliveira@forvismazars.com', '2840', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Isabel Cristina Dos Anjos Caetano', 'isabel.caetano@forvismazars.com', '0800', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Juliana Midori Yoshida Carlota', 'juliana.carlota@forvismazars.com', '8888', 'BPO- CONTÁBIL', 'Analista'),
  ('Marcela Vieira Tarden Magalhaes', 'marcela.magalhaes@forvismazars.com', '6705', 'BPO- FINANCEIRO', 'Assistente'),
  ('Rodrigo Ferreira De Gouvea', 'rodrigo.gouvea@forvismazars.com', '7720', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Sophia Vertuan Venovichi Dias', 'sophia.dias@forvismazars.com', '2863', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Melissa Gomes Siman Novais', 'melissa.siman@forvismazars.com', '5858', 'BPO- FINANCEIRO', 'Assistente'),
  ('Acza Pereira Da Silva', 'acza.silva@forvismazars.com', '7829', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Angelo Silva De Souza', 'angelo.souza@forvismazars.com', '3755', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Cassio Habacuque Da Silva Barros', 'cassio.silva@forvismazars.com', '4742', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Carolina Da Silva Rocha', 'carolina.silva@forvismazars.com', '9838', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Jefferson Francisco De Oliveira', 'jefferson.oliveira@forvismazars.com', '7809', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Silvia Regina Da Fonseca Silva', 'silvia.fonseca@forvismazars.com', '9713', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Luciano Nappi Junior', 'luciano.junior@forvismazars.com', '9816', 'BPO- CONTÁBIL', 'Analista'),
  ('Jessica Da Silva Almeida', 'jessica.almeida@forvismazars.com', '0819', 'BPO- CONTÁBIL', 'Analista'),
  ('Andreia Souza Pinheiro Dias', 'andreia.dias@forvismazars.com', '8817', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Fabiana Cortes Cardoso Oliveira', 'fabiana.oliveira@forvismazars.com', '5842', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Aline Aparecida Lira Alves', 'aline.alves@forvismazars.com', '8880', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Americo Da Silva Teixeira Junior', 'americo.junior@forvismazars.com', '3746', 'BPO- FISCAL INDIRETOS', 'Auxiliar'),
  ('Daniel Lucas Domingos Lourenco', 'daniel.lourenco@forvismazars.com', '3559', 'BPO- FINANCEIRO', 'Analista'),
  ('Aniele Carvalho De Jesus', 'aniele.jesus@forvismazars.com', '0792', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Ana Cassia Silva Soares', 'ana.soares@forvismazars.com', '0735', 'BPO- CONTÁBIL', 'Assistente'),
  ('Mayara Mendes Ribeiro', 'mayara.ribeiro@forvismazars.com', '7706', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Rebeca Soares Da Costa', 'rebeca.costa@forvismazars.com', '2845', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Tatiane Marielen Gaspar', 'tatiane.gaspar@forvismazars.com', '5876', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Maria Eduarda Roveri', 'maria.roveri@forvismazars.com', '4839', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Elaine Cesaretti Porto', 'elaine.porto@forvismazars.com', '7862', 'BPO- CONTÁBIL', 'Analista'),
  ('Evelyn Medeiros Carvalho Moraes', 'evelyn.moraes@forvismazars.com', '1836', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Liliani Poretto Gabatel', 'liliani.gabatel@forvismazars.com', '6808', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Ramson Vieira Da Silva Junior', 'ramson.junior@forvismazars.com', '5875', 'BPO- FISCAL INDIRETOS', 'Supervisor'),
  ('Marcela Ribeiro Stenico', 'marcela.stenico@forvismazars.com', '7838', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Andreza Burghardt', 'andreza.burghardt@forvismazars.com', '6927', 'BPO- FOLHA DE PAGAMENTO', 'Analista'),
  ('Daiane Medeiros Pires Godoi', 'daiane.godoi@forvismazars.com', '6809', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Jose Eduardo Cabrera Fernandes', 'eduardo.cabrera@forvismazars.com', '0826', 'COMEX', 'Socio'),
  ('Mario Luiz Alves Da Costa', 'mario.costa@forvismazars.com', '0700', 'CONSULTORIA EMPRESARIAL- RISK CONSULTING', 'Diretor'),
  ('Felipe Augusto Batoni De Souza', 'felipe.batoni@forvismazars.com', '9857', 'CONSULTORIA EMPRESARIAL- DIGITAL', 'Supervisor'),
  ('Jefferson Rodrigues Da Silva', 'jefferson.silva@forvismazars.com', '6897', 'CONSULTORIA EMPRESARIAL- RISK CONSULTING', 'Estagiario'),
  ('Jaqueline Aparecida Da Costa', 'jaqueline.costa@forvismazars.com', '0877', 'FINANCIAL ADVISORY- VALUATION', 'Senior'),
  ('Mariana Dourado Prates', 'mariana.dourado@forvismazars.com', '5518', 'TAX - CONSULTING', 'Diretor'),
  ('Sergio De Almeida Narciso Gomes Junior', 'sergio.gomes@forvismazars.com', '7820', 'TAX - CONSULTING', 'Diretor'),
  ('Mayara Teles Moreira', 'mayara.teles@forvismazars.com', '6713', 'BPO- FISCAL INDIRETOS', 'Analista'),
  ('Adrielle Cristina Dreger', 'adrielle.dreger@forvismazars.com', '7847', 'TAX - CONSULTING', 'Senior'),
  ('Leonardo Marinello Da Silva Dantas', 'leonardo.dantas@forvismazars.com', '7837', 'AUDITORIA', 'Senior'),
  ('Francisco Robson Soares De Sousa', 'francisco.sousa@forvismazars.com', '3850', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Mayra Silva De Oliveira', 'mayra.oliveira@forvismazars.com', '4855', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Karina Oliveira De Azevedo Zerbato', 'karina.zerbato@forvismazars.com', '9863', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Vinicius Guimaraes Ribeiro', 'vinicius.ribeiro@forvismazars.com', '3673', 'CONSULTORIA EMPRESARIAL- RISK CONSULTING', 'Gerente'),
  ('Julio Cesar Goncalves Da Silva', 'julio.silva@forvismazars.com', '1803', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Tamires Fatima De Sousa Teixeira', 'tamires.teixeira@forvismazars.com', '4800', 'BPO- CONTÁBIL', 'Assistente'),
  ('Carolina Miranda Cavalcante', 'carolina.cavalcante@forvismazars.com', '3812', 'TAX - CONSULTING', 'Trainee'),
  ('Pedro De Alcantara Oliveira Penteado Vargas', 'pedro.vargas@forvismazars.com', '6808', 'CONSULTORIA EMPRESARIAL- RISK CONSULTING', 'Consultor'),
  ('Thamara Gleice De Souza Braz', 'thamara.braz@forvismazars.com', '2836', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Fernanda Sapucaia Saturno', 'fernanda.saturno@forvismazars.com', '1866', 'CONTROLADORIA', 'Analista'),
  ('Lucas Nobrega De Jesus', 'lucas.nobrega@forvismazars.com', '3857', 'BPO- FISCAL DIRETOS', 'Analista'),
  ('Ludimila Fernanda Souza Galeigo', 'ludimila.galeigo@forvismazars.com', '1819', 'AUDITORIA', 'Senior'),
  ('Guilherme Yuri Belchior Balbino', 'guilherme.balbino@forvismazars.com', '0861', 'BPO- CONTÁBIL', 'Analista'),
  ('Nathalia Audrey Cardoso', 'nathalia.audrey@forvismazars.com', '0864', 'BUSINESS DEVELOPMENT', 'Consultor'),
  ('Thiago Costa Gomes Da Silva', 'thiago.silva@forvismazars.com', '2733', 'BPO- FOLHA DE PAGAMENTO', 'Analista'),
  ('Juliele Santos De Carvalho', 'juliele.carvalho@forvismazars.com', '0803', 'TI', 'Analista'),
  ('Carolina Milczanowski Dos Santos', 'carolina.milczanowski@forvismazars.com', '6736', 'BPO- CONTÁBIL', 'Assistente'),
  ('Mateus Garbo Marques', 'mateus.marques@forvismazars.com', '1859', 'BPO- IMPLANTAÇÃO NETCORP', 'Estagiario'),
  ('Cintia Da Silva Inacio Santos', 'cintia.santos@forvismazars.com', '7835', 'GENTE&GESTÃO', 'Analista'),
  ('Larissa Beatriz Leite', 'larissa.leite@forvismazars.com', '8267', 'BPO- CONTÁBIL', 'Analista'),
  ('Lucas Viegas Rocha Garcia', 'lucas.garcia@forvismazars.com', '0741', 'BPO- CONTÁBIL', 'Assistente'),
  ('Eduardo Farkuh Pedreira De Queiroz', 'eduardo.queiroz@forvismazars.com', '5886', 'BPO- CONTÁBIL', 'Gerente'),
  ('Arthur Henrique Weiss De Amorim', 'arthur.amorim@forvismazars.com', '3960', 'BPO- FOLHA DE PAGAMENTO', 'Supervisor'),
  ('Thayna Carvalho Alves', 'thayna.alves@forvismazars.com', '2718', 'BPO- CONTÁBIL', 'Analista'),
  ('Vinicius Domiciano Mendonca', 'vinicius.mendonca@forvismazars.com', '9830', 'FINANCIAL ADVISORY- VALUATION', 'Senior'),
  ('Guilherme Henrique Sousa Silva', 'guilherme.silva@forvismazars.com', '5862', 'CONSULTORIA EMPRESARIAL- RISK CONSULTING', 'Estagiario'),
  ('Igor Souza Da Cruz', 'igor.cruz@forvismazars.com', '5796', 'AUDITORIA', 'Assistente'),
  ('Jean Roberto Gomes', 'jean.gomes@forvismazars.com', '6816', 'CONSULTORIA EMPRESARIAL- RISK CONSULTING', 'Estagiario'),
  ('Marcela Silva De Sousa', 'marcela.sousa@forvismazars.com', '1700', 'BPO- CONTÁBIL', 'Assistente'),
  ('Marina Dos Santos Britto', 'marina.britto@forvismazars.com', '8838', 'BPO- CONTÁBIL', 'Analista'),
  ('Giovanna Herrerias Cabrera', 'giovanna.cabrera@forvismazars.com', '3880', 'TREINAMENTO&DESENVOLVIMENTO', 'Assistente'),
  ('Greicy Eloisa Benuti Gomes', 'greicy.eloisa@forvismazars.com', '9832', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Gabriel Caires De Moraes', 'gabriel.moraes@forvismazars.com', '4783', 'AUDITORIA', 'Senior'),
  ('Beatriz Guimaraes Lucas', 'beatriz.lucas@forvismazars.com', '2801', 'TAX- DUE DILIGENCE', 'Senior'),
  ('Jacir Jose Zanluca', 'jacir.zanluca@forvismazars.com', '2986', 'AUDITORIA', 'Senior'),
  ('Samara Regina Vasconcelos Mendes', 'samara.mendes@forvismazars.com', '7597', 'JURIDICO', 'Analista'),
  ('Glenda Maui Spedine Nascimento', 'glenda.nascimento@forvismazars.com', '3817', 'TAX - CONSULTING', 'Trainee'),
  ('Shayene Emily Goncalves Dos Santos', 'shayene.santos@forvismazars.com', '0801', 'AUDITORIA', 'Assistente'),
  ('Jhonatan Menegatti Da Silva', 'jhonatan.silva@forvismazars.com', '1943', 'AUDITORIA', 'Assistente'),
  ('Gabriela Fernandes Souza Da Silva', 'gabriela.fernandes@forvismazars.com', '3802', 'JURIDICO', 'Analista'),
  ('Arthur Miranda Silva', 'arthur.miranda@forvismazars.com', '4841', 'TAX - CONSULTING', 'Trainee'),
  ('Fabio Ozaki', 'fabio.ozaki@forvismazars.com', '1841', 'CONSULTORIA EMPRESARIAL- RISK CONSULTING', 'Prestador de Serviços'),
  ('Diego Pereira Batista', 'diego.batista@forvismazars.com', '4806', 'BPO- CONTÁBIL', 'Supervisor'),
  ('Pedro Henrique Sales De Castro', 'pedro.castro@forvismazars.com', '4336', 'AUDITORIA', 'Trainee'),
  ('Pamela Pereira Biscaino', 'pamela.biscaino@forvismazars.com', '3817', 'BPO- CONTÁBIL', 'Assistente'),
  ('Adrielly Da Silva Moura', 'adrielly.moura@forvismazars.com', '9803', 'BPO- CONTÁBIL', 'Analista'),
  ('Rafael Guilherme Rabelo Alves', 'rafael.rabelo@forvismazars.com', '8319', 'AUDITORIA', 'Assistente'),
  ('Jhonatan De Sousa Ferreira', 'jhonatan.ferreira@forvismazars.com', '2882', 'BPO- CONTÁBIL', 'Assistente'),
  ('Andressa Antunes De Farias', 'andressa.farias@forvismazars.com', '8870', 'BPO- CONTÁBIL', 'Assistente'),
  ('Luis Fernando Fernandes Sanches', 'luis.sanches@forvismazars.com', '5804', 'BPO- CONTÁBIL', 'Assistente'),
  ('Samuel Cavalcanti Do Amaral', 'samuel.amaral@forvismazars.com', '3777', 'BPO- CONTÁBIL', 'Analista'),
  ('Dilce Aparecida Hernandes Mequineli', 'dilce.mequineli@forvismazars.com', '5801', 'BPO- CONTRATAÇÃO STAFF LOAN', 'Analista'),
  ('Evelly Orquidea Costa Martiniano', 'evelly.martiano@forvismazars.com', '9350', 'AUDITORIA', 'Trainee'),
  ('Thiago Bordinhao Marins', 'thiago.marins@forvismazars.com', '8757', 'AUDITORIA', 'Senior'),
  ('Walter Cordeiro Guilhermino', 'walter.guilhermino@forvismazars.com', '4896', 'AUDITORIA', 'Trainee'),
  ('Cassia Adriana Dos Santos Lorena', 'cassia.lorena@forvismazars.com', '2826', 'CONTROLADORIA', 'Analista'),
  ('Thiago Henrique Stranghetti', 'thiago.stranghetti@forvismazars.com', '0843', 'TI', 'Analista'),
  ('Uly Lambert Bezerra', 'uly.bezerra@forvismazars.com', '1867', 'BPO- FISCAL INDIRETOS', 'Assistente'),
  ('Keuany Vitoria Da Silva Barbosa', 'keuany.barbosa@forvismazars.com', '1701', 'BPO- CONTÁBIL', 'Assistente'),
  ('Leticia Aparecida Dos Santos', 'leticia.santos@forvismazars.com', '0831', 'BPO- FISCAL DIRETOS', 'Analista'),
  ('Larissa Dauane De Carvalho Rodrigues', 'larissa.rodrigues@forvismazars.com', '2952', 'BPO- CONTÁBIL', 'Analista'),
  ('Thaylor Tiago De Jesus Santos', 'thaylor.santos@forvismazars.com', '1897', 'BPO- FISCAL INDIRETOS', 'Assistente'),
  ('Fayna Bento De Almeida', 'fayna.almeida@forvismazars.com', '8720', 'BPO- FINANCEIRO', 'Assistente'),
  ('Laisa Kauane Rodrigues', 'laisa.rodrigues@forvismazars.com', '6921', 'BPO- CONTÁBIL', 'Assistente'),
  ('Maria Eduarda De Liz Leite', 'maria.leite@forvismazars.com', '4907', 'FINANCIAL ADVISORY- VALUATION', 'Trainee'),
  ('Eduardo Luis Bossani Campagnolo', 'eduardo.campagnolo@forvismazars.com', '5831', 'BPO- FISCAL INDIRETOS', 'Assistente'),
  ('Alexandre Aparecido Piassa', 'alexandre.piassa@forvismazars.com', '8809', 'BPO- FISCAL INDIRETOS', 'Analista'),
  ('Raulph De Moraes', 'rualph.moraes@forvismazars.com', '3954', 'FINANCIAL ADVISORY- VALUATION', 'Trainee'),
  ('Thais Marques Dos Santos', 'thais.santos@forvismazars.com', '5858', 'FINANCIAL ADVISORY- ATIVO FIXO', 'Trainee'),
  ('Matheus Cesar Fincatti Dos Santos', 'matheus.fincatti@forvismazars.com', '4806', 'FINANCIAL ADVISORY- ATIVO FIXO', 'Trainee'),
  ('Pedro Soares Fernandes Rezende', 'pedro.dias@forvismazars.com', '1842', 'FINANCIAL ADVISORY- VALUATION', 'Trainee'),
  ('Stefany Do Nascimento Matos', 'stefany.matos@forvismazars.com', '4898', 'BPO- CONTÁBIL', 'Assistente'),
  ('Paulo Henrique Hirata Diethelm', 'paulo.diethelm@forvismazars.com', '4875', 'FINANCIAL ADVISORY- ATIVO FIXO', 'Trainee'),
  ('Nadyne Duarte Iocksch', 'nadyne.locksh@forvismazars.com', '0001', 'FINANCIAL ADVISORY- ATIVO FIXO', 'Senior')
) AS v(nome, email, cpf, area, cargo)
WHERE NOT EXISTS (
  SELECT 1 FROM public.profiles p WHERE LOWER(p.email) = LOWER(v.email)
);